// 默认菜单数据配置
// 基于数据库表 sys_permission 的结构
export const defaultMenus = [
  {
    id: 1,
    permissionCode: 'data-center',
    permissionName: '数据中心',
    permissionType: 'menu',
    parentId: 0,
    path: '/data-center',
    component: 'Layout',
    icon: 'DatabaseOutlined',
    sortOrder: 1,
    status: 1,
    children: [
      {
        id: 2,
        permissionCode: 'data-datasource',
        permissionName: '数据源管理',
        permissionType: 'menu',
        parentId: 1,
        path: '/datasource',
        component: 'DataSource',
        icon: 'CloudServerOutlined',
        sortOrder: 1,
        status: 1,
      },
      {
        id: 3,
        permissionCode: 'data-collect',
        permissionName: '数据采集',
        permissionType: 'menu',
        parentId: 1,
        path: '/collect',
        component: 'Collect',
        icon: 'CloudDownloadOutlined',
        sortOrder: 2,
        status: 1,
      },
      {
        id: 4,
        permissionCode: 'data-process',
        permissionName: '数据处理',
        permissionType: 'menu',
        parentId: 1,
        path: '/processing',
        component: 'Processing',
        icon: 'ToolOutlined',
        sortOrder: 3,
        status: 1,
      },
      {
        id: 5,
        permissionCode: 'data-annotation',
        permissionName: '数据标注',
        permissionType: 'menu',
        parentId: 1,
        path: '/annotation',
        component: 'Annotation',
        icon: 'EditOutlined',
        sortOrder: 4,
        status: 1,
      },
      {
        id: 6,
        permissionCode: 'data-augment',
        permissionName: '数据增强',
        permissionType: 'menu',
        parentId: 1,
        path: '/augment',
        component: 'Augment',
        icon: 'PlusOutlined',
        sortOrder: 5,
        status: 1,
      },
      {
        id: 7,
        permissionCode: 'data-synthesis',
        permissionName: '数据合成',
        permissionType: 'menu',
        parentId: 1,
        path: '/synthesis',
        component: 'Synthesis',
        icon: 'MergeCellsOutlined',
        sortOrder: 6,
        status: 1,
      },
      {
        id: 8,
        permissionCode: 'data-evaluation',
        permissionName: '数据评估',
        permissionType: 'menu',
        parentId: 1,
        path: '/evaluation',
        component: 'Evaluation',
        icon: 'BarChartOutlined',
        sortOrder: 7,
        status: 1,
      },
      {
        id: 9,
        permissionCode: 'data-reflow',
        permissionName: '数据回流',
        permissionType: 'menu',
        parentId: 1,
        path: '/reflow',
        component: 'Reflow',
        icon: 'ReloadOutlined',
        sortOrder: 8,
        status: 1,
      },
    ],
  },
  {
    id: 10,
    permissionCode: 'data-market',
    permissionName: '数据市场',
    permissionType: 'menu',
    parentId: 0,
    path: '/data-market',
    component: 'Layout',
    icon: 'ShoppingOutlined',
    sortOrder: 2,
    status: 1,
    children: [
      {
        id: 11,
        permissionCode: 'dataset-list',
        permissionName: '数据集列表',
        permissionType: 'menu',
        parentId: 10,
        path: '/dataset',
        component: 'Dataset',
        icon: 'UnorderedListOutlined',
        sortOrder: 1,
        status: 1,
      },
      {
        id: 12,
        permissionCode: 'compliance-check',
        permissionName: '合规检测',
        permissionType: 'menu',
        parentId: 10,
        path: '/compliance',
        component: 'Compliance',
        icon: 'SafetyCertificateOutlined',
        sortOrder: 2,
        status: 1,
      },
      {
        id: 13,
        permissionCode: 'transaction-record',
        permissionName: '交易记录',
        permissionType: 'menu',
        parentId: 10,
        path: '/transaction',
        component: 'Transaction',
        icon: 'TransactionOutlined',
        sortOrder: 3,
        status: 1,
      },
      {
        id: 14,
        permissionCode: 'user-rating',
        permissionName: '用户评分/举报',
        permissionType: 'menu',
        parentId: 10,
        path: '/rating',
        component: 'Rating',
        icon: 'StarOutlined',
        sortOrder: 4,
        status: 1,
      },
    ],
  },
  {
    id: 15,
    permissionCode: 'data-compliance',
    permissionName: '数据合规',
    permissionType: 'menu',
    parentId: 0,
    path: '/data-compliance',
    component: 'Layout',
    icon: 'SafetyOutlined',
    sortOrder: 3,
    status: 1,
    children: [
      {
        id: 16,
        permissionCode: 'privacy-compliance',
        permissionName: '隐私合规检测',
        permissionType: 'menu',
        parentId: 15,
        path: '/privacy',
        component: 'Privacy',
        icon: 'EyeInvisibleOutlined',
        sortOrder: 1,
        status: 1,
      },
      {
        id: 17,
        permissionCode: 'desensitization-tool',
        permissionName: '脱敏工具',
        permissionType: 'menu',
        parentId: 15,
        path: '/desensitization',
        component: 'Desensitization',
        icon: 'LockOutlined',
        sortOrder: 2,
        status: 1,
      },
      {
        id: 18,
        permissionCode: 'audit-log',
        permissionName: '审计日志',
        permissionType: 'menu',
        parentId: 15,
        path: '/audit',
        component: 'Audit',
        icon: 'FileTextOutlined',
        sortOrder: 3,
        status: 1,
      },
    ],
  },
  {
    id: 19,
    permissionCode: 'data-insight',
    permissionName: '数据洞察',
    permissionType: 'menu',
    parentId: 0,
    path: '/data-insight',
    component: 'Layout',
    icon: 'BarChartOutlined',
    sortOrder: 4,
    status: 1,
    children: [
      {
        id: 20,
        permissionCode: 'data-overview',
        permissionName: '数据概览',
        permissionType: 'menu',
        parentId: 19,
        path: '/overview',
        component: 'Overview',
        icon: 'DashboardOutlined',
        sortOrder: 1,
        status: 1,
      },
      {
        id: 21,
        permissionCode: 'bias-trend',
        permissionName: '偏差趋势',
        permissionType: 'menu',
        parentId: 19,
        path: '/bias',
        component: 'Bias',
        icon: 'TrendingUpOutlined',
        sortOrder: 2,
        status: 1,
      },
      {
        id: 22,
        permissionCode: 'report-export',
        permissionName: '报表导出',
        permissionType: 'menu',
        parentId: 19,
        path: '/report',
        component: 'Report',
        icon: 'ExportOutlined',
        sortOrder: 3,
        status: 1,
      },
    ],
  },
  {
    id: 23,
    permissionCode: 'model-center',
    permissionName: '模型中心',
    permissionType: 'menu',
    parentId: 0,
    path: '/model-center',
    component: 'Layout',
    icon: 'RobotOutlined',
    sortOrder: 5,
    status: 1,
    children: [
      {
        id: 24,
        permissionCode: 'model-management',
        permissionName: '模型管理',
        permissionType: 'menu',
        parentId: 23,
        path: '/model-management',
        component: 'Management',
        icon: 'AppstoreOutlined',
        sortOrder: 1,
        status: 1,
      },
      {
        id: 25,
        permissionCode: 'model-training',
        permissionName: '模型训练',
        permissionType: 'menu',
        parentId: 23,
        path: '/model-training',
        component: 'Training',
        icon: 'PlayCircleOutlined',
        sortOrder: 2,
        status: 1,
      },
      {
        id: 26,
        permissionCode: 'model-evaluation',
        permissionName: '模型评估',
        permissionType: 'menu',
        parentId: 23,
        path: '/model-evaluation',
        component: 'Evaluation',
        icon: 'CheckCircleOutlined',
        sortOrder: 3,
        status: 1,
      },
      {
        id: 27,
        permissionCode: 'model-deployment',
        permissionName: '模型部署',
        permissionType: 'menu',
        parentId: 23,
        path: '/model-deployment',
        component: 'Deployment',
        icon: 'RocketOutlined',
        sortOrder: 4,
        status: 1,
      },
      {
        id: 28,
        permissionCode: 'model-inference',
        permissionName: '模型推理',
        permissionType: 'menu',
        parentId: 23,
        path: '/model-inference',
        component: 'Inference',
        icon: 'ThunderboltOutlined',
        sortOrder: 5,
        status: 1,
      },
    ],
  },
  {
    id: 29,
    permissionCode: 'model-market',
    permissionName: '模型市场',
    permissionType: 'menu',
    parentId: 0,
    path: '/model-market',
    component: 'Layout',
    icon: 'ShopOutlined',
    sortOrder: 6,
    status: 1,
    children: [
      {
        id: 30,
        permissionCode: 'model-listing',
        permissionName: '模型上架',
        permissionType: 'menu',
        parentId: 29,
        path: '/model-listing',
        component: 'Listing',
        icon: 'UploadOutlined',
        sortOrder: 1,
        status: 1,
      },
      {
        id: 31,
        permissionCode: 'model-compliance',
        permissionName: '合规检测',
        permissionType: 'menu',
        parentId: 29,
        path: '/model-compliance',
        component: 'Compliance',
        icon: 'SafetyCertificateOutlined',
        sortOrder: 2,
        status: 1,
      },
      {
        id: 32,
        permissionCode: 'call-statistics',
        permissionName: '调用统计',
        permissionType: 'menu',
        parentId: 29,
        path: '/call-statistics',
        component: 'Statistics',
        icon: 'BarChartOutlined',
        sortOrder: 3,
        status: 1,
      },
      {
        id: 33,
        permissionCode: 'model-rating',
        permissionName: '用户评分',
        permissionType: 'menu',
        parentId: 29,
        path: '/model-rating',
        component: 'Rating',
        icon: 'StarOutlined',
        sortOrder: 4,
        status: 1,
      },
    ],
  },
  {
    id: 34,
    permissionCode: 'workflow',
    permissionName: '工作流编排',
    permissionType: 'menu',
    parentId: 0,
    path: '/workflow',
    component: 'Layout',
    icon: 'DeploymentUnitOutlined',
    sortOrder: 7,
    status: 1,
    children: [
      {
        id: 35,
        permissionCode: 'visual-task-flow',
        permissionName: '可视化任务流',
        permissionType: 'menu',
        parentId: 34,
        path: '/visual-task-flow',
        component: 'Visual',
        icon: 'NodeIndexOutlined',
        sortOrder: 1,
        status: 1,
      },
      {
        id: 36,
        permissionCode: 'schedule-management',
        permissionName: '调度管理',
        permissionType: 'menu',
        parentId: 34,
        path: '/schedule-management',
        component: 'Schedule',
        icon: 'ClockCircleOutlined',
        sortOrder: 2,
        status: 1,
      },
    ],
  },
  {
    id: 37,
    permissionCode: 'billing-center',
    permissionName: '账单中心',
    permissionType: 'menu',
    parentId: 0,
    path: '/billing-center',
    component: 'Layout',
    icon: 'CreditCardOutlined',
    sortOrder: 8,
    status: 1,
    children: [
      {
        id: 38,
        permissionCode: 'data-billing',
        permissionName: '数据账单',
        permissionType: 'menu',
        parentId: 37,
        path: '/data-billing',
        component: 'Data',
        icon: 'FileTextOutlined',
        sortOrder: 1,
        status: 1,
      },
      {
        id: 39,
        permissionCode: 'model-billing',
        permissionName: '模型账单',
        permissionType: 'menu',
        parentId: 37,
        path: '/model-billing',
        component: 'Model',
        icon: 'FileTextOutlined',
        sortOrder: 2,
        status: 1,
      },
    ],
  },
  {
    id: 40,
    permissionCode: 'system-management',
    permissionName: '系统管理',
    permissionType: 'menu',
    parentId: 0,
    path: '/system-management',
    component: 'Layout',
    icon: 'SettingOutlined',
    sortOrder: 9,
    status: 1,
    children: [
      {
        id: 41,
        permissionCode: 'user-management',
        permissionName: '用户管理',
        permissionType: 'menu',
        parentId: 40,
        path: '/system-management/user',
        component: 'SystemManagement/User',
        icon: 'UserOutlined',
        sortOrder: 1,
        status: 1,
      },
      {
        id: 42,
        permissionCode: 'tenant-management',
        permissionName: '租户管理',
        permissionType: 'menu',
        parentId: 40,
        path: '/system-management/tenant',
        component: 'SystemManagement/Tenant',
        icon: 'TeamOutlined',
        sortOrder: 2,
        status: 1,
      },
      {
        id: 43,
        permissionCode: 'role-permission',
        permissionName: '权限角色',
        permissionType: 'menu',
        parentId: 40,
        path: '/system-management/role',
        component: 'SystemManagement/Role',
        icon: 'KeyOutlined',
        sortOrder: 3,
        status: 1,
      },
      {
        id: 44,
        permissionCode: 'project-management',
        permissionName: '项目管理',
        permissionType: 'menu',
        parentId: 40,
        path: '/system-management/project',
        component: 'SystemManagement/Project',
        icon: 'ProjectOutlined',
        sortOrder: 4,
        status: 1,
      },
      {
        id: 45,
        permissionCode: 'environment-config',
        permissionName: '环境配置',
        permissionType: 'menu',
        parentId: 40,
        path: '/system-management/config',
        component: 'SystemManagement/Config',
        icon: 'ToolOutlined',
        sortOrder: 5,
        status: 1,
      },
    ],
  },
  {
    id: 46,
    permissionCode: 'experiment-tools',
    permissionName: '实验工具',
    permissionType: 'menu',
    parentId: 0,
    path: '/experiment-tools',
    component: 'Layout',
    icon: 'ExperimentOutlined',
    sortOrder: 10,
    status: 1,
    children: [
      {
        id: 47,
        permissionCode: 'vscode',
        permissionName: 'VSCode',
        permissionType: 'menu',
        parentId: 46,
        path: '/vscode',
        component: 'VSCode',
        icon: 'CodeOutlined',
        sortOrder: 1,
        status: 1,
      },
      {
        id: 48,
        permissionCode: 'jupyterlab',
        permissionName: 'JupyterLab',
        permissionType: 'menu',
        parentId: 46,
        path: '/jupyterlab',
        component: 'JupyterLab',
        icon: 'BookOutlined',
        sortOrder: 2,
        status: 1,
      },
    ],
  },
];

export default defaultMenus;
